[package]
name = "skyblock"
description = "skyblock client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
skyblock-proto.workspace = true
skyblock-sys.workspace = true
anyhow.workspace = true
clap.workspace = true
ctrlc = "3"
ipnet.workspace = true
rand.workspace = true
serde.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_IpHelper",
    "Win32_Networking_WinSock",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_IO",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
]
